version: 3

env:
  PATH_MAIN: cmd/core-accounts/main.go
  PATH_DEV_CFG: config/dev.yaml
  PATH_LOCAL_CFG: config/local.yaml
  PATH_MIGRATION_PSQL_DIR: migration/pgx_goose_migration

  PROTO_SRC: proto
  PROTO_OUT: gogen

tasks:
  dev:
    cmds:
      - CONFIG_PATH=$PATH_DEV_CFG go run -race $PATH_MAIN run

  proto:
    desc: "Generate Go code from all proto files"
    cmds:
      - |
        sh -c '
          PROTO_FILES=$(find {{.PROTO_SRC}} -name "*.proto");
          protoc \
            --proto_path={{.PROTO_SRC}}/third_party \
            --proto_path={{.PROTO_SRC}} \
            $PROTO_FILES \
            --go-grpc_opt=require_unimplemented_servers=false \
            --go_out={{.PROTO_OUT}} \
            --go_opt=paths=source_relative \
            --go-grpc_out={{.PROTO_OUT}} \
            --go-grpc_opt=paths=source_relative
        '
  migration:
    # goose -dir migration/postgres create name_file sql
    cmds:
      - export GOOSE_DRIVER=postgres
      - export GOOSE_DBSTRING=postgresql://eer0:secret@localhost:10101/accounts?sslmode=disable
      - export GOOSE_MIGRATION_DIR=migration/postgres
      - goose up