// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: query/v1/query.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryOrder int32

const (
	QueryOrder_ASK  QueryOrder = 0
	QueryOrder_DESK QueryOrder = 1
)

// Enum value maps for QueryOrder.
var (
	QueryOrder_name = map[int32]string{
		0: "ASK",
		1: "DESK",
	}
	QueryOrder_value = map[string]int32{
		"ASK":  0,
		"DESK": 1,
	}
)

func (x QueryOrder) Enum() *QueryOrder {
	p := new(QueryOrder)
	*p = x
	return p
}

func (x QueryOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_query_v1_query_proto_enumTypes[0].Descriptor()
}

func (QueryOrder) Type() protoreflect.EnumType {
	return &file_query_v1_query_proto_enumTypes[0]
}

func (x QueryOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryOrder.Descriptor instead.
func (QueryOrder) EnumDescriptor() ([]byte, []int) {
	return file_query_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	OrderBy       QueryOrder             `protobuf:"varint,4,opt,name=order_by,json=orderBy,proto3,enum=query.QueryOrder" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryData) Reset() {
	*x = QueryData{}
	mi := &file_query_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryData) ProtoMessage() {}

func (x *QueryData) ProtoReflect() protoreflect.Message {
	mi := &file_query_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryData.ProtoReflect.Descriptor instead.
func (*QueryData) Descriptor() ([]byte, []int) {
	return file_query_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryData) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryData) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryData) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *QueryData) GetOrderBy() QueryOrder {
	if x != nil {
		return x.OrderBy
	}
	return QueryOrder_ASK
}

var File_query_v1_query_proto protoreflect.FileDescriptor

const file_query_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x14query/v1/query.proto\x12\x05query\"|\n" +
	"\tQueryData\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12,\n" +
	"\border_by\x18\x04 \x01(\x0e2\x11.query.QueryOrderR\aorderBy*\x1f\n" +
	"\n" +
	"QueryOrder\x12\a\n" +
	"\x03ASK\x10\x00\x12\b\n" +
	"\x04DESK\x10\x01B1Z/github.com/OddKuru/core-accounts/gogen/query/v1b\x06proto3"

var (
	file_query_v1_query_proto_rawDescOnce sync.Once
	file_query_v1_query_proto_rawDescData []byte
)

func file_query_v1_query_proto_rawDescGZIP() []byte {
	file_query_v1_query_proto_rawDescOnce.Do(func() {
		file_query_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_v1_query_proto_rawDesc), len(file_query_v1_query_proto_rawDesc)))
	})
	return file_query_v1_query_proto_rawDescData
}

var file_query_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_query_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_query_v1_query_proto_goTypes = []any{
	(QueryOrder)(0),   // 0: query.QueryOrder
	(*QueryData)(nil), // 1: query.QueryData
}
var file_query_v1_query_proto_depIdxs = []int32{
	0, // 0: query.QueryData.order_by:type_name -> query.QueryOrder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_query_v1_query_proto_init() }
func file_query_v1_query_proto_init() {
	if File_query_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_v1_query_proto_rawDesc), len(file_query_v1_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_v1_query_proto_goTypes,
		DependencyIndexes: file_query_v1_query_proto_depIdxs,
		EnumInfos:         file_query_v1_query_proto_enumTypes,
		MessageInfos:      file_query_v1_query_proto_msgTypes,
	}.Build()
	File_query_v1_query_proto = out.File
	file_query_v1_query_proto_goTypes = nil
	file_query_v1_query_proto_depIdxs = nil
}
