// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: accounts/v1/accounts.proto

package v1

import (
	v1 "github.com/OddKuru/core-accounts/gogen/query/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_accounts_v1_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_v1_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_accounts_v1_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_accounts_v1_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_v1_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_accounts_v1_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_accounts_v1_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_v1_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_accounts_v1_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateNameByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNameByIdRequest) Reset() {
	*x = UpdateNameByIdRequest{}
	mi := &file_accounts_v1_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNameByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNameByIdRequest) ProtoMessage() {}

func (x *UpdateNameByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_v1_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNameByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateNameByIdRequest) Descriptor() ([]byte, []int) {
	return file_accounts_v1_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNameByIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateNameByIdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateEmailByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailByIdRequest) Reset() {
	*x = UpdateEmailByIdRequest{}
	mi := &file_accounts_v1_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailByIdRequest) ProtoMessage() {}

func (x *UpdateEmailByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_v1_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailByIdRequest) Descriptor() ([]byte, []int) {
	return file_accounts_v1_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEmailByIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateEmailByIdRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateRoleByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleByIdRequest) Reset() {
	*x = UpdateRoleByIdRequest{}
	mi := &file_accounts_v1_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleByIdRequest) ProtoMessage() {}

func (x *UpdateRoleByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_v1_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleByIdRequest) Descriptor() ([]byte, []int) {
	return file_accounts_v1_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoleByIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateRoleByIdRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdatePasswordByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordByIdRequest) Reset() {
	*x = UpdatePasswordByIdRequest{}
	mi := &file_accounts_v1_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordByIdRequest) ProtoMessage() {}

func (x *UpdatePasswordByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_v1_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordByIdRequest) Descriptor() ([]byte, []int) {
	return file_accounts_v1_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePasswordByIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdatePasswordByIdRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordByIdRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type QueryAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	PageCount     uint64                 `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAccountsResponse) Reset() {
	*x = QueryAccountsResponse{}
	mi := &file_accounts_v1_accounts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccountsResponse) ProtoMessage() {}

func (x *QueryAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_v1_accounts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccountsResponse.ProtoReflect.Descriptor instead.
func (*QueryAccountsResponse) Descriptor() ([]byte, []int) {
	return file_accounts_v1_accounts_proto_rawDescGZIP(), []int{7}
}

func (x *QueryAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *QueryAccountsResponse) GetPageCount() uint64 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

var File_accounts_v1_accounts_proto protoreflect.FileDescriptor

const file_accounts_v1_accounts_proto_rawDesc = "" +
	"\n" +
	"\x1aaccounts/v1/accounts.proto\x12\vaccounts.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14query/v1/query.proto\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcd\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\\\n" +
	"\x14CreateAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"J\n" +
	"\x15UpdateNameByIdRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"M\n" +
	"\x16UpdateEmailByIdRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"J\n" +
	"\x15UpdateRoleByIdRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x80\x01\n" +
	"\x19UpdatePasswordByIdRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"h\n" +
	"\x15QueryAccountsResponse\x120\n" +
	"\baccounts\x18\x01 \x03(\v2\x14.accounts.v1.AccountR\baccounts\x12\x1d\n" +
	"\n" +
	"page_count\x18\x02 \x01(\x04R\tpageCount2\xdb\x05\n" +
	"\x0fAccountsService\x12Y\n" +
	"\x06Create\x12!.accounts.v1.CreateAccountRequest\x1a\x14.accounts.v1.Account\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\vv1/accounts\x12i\n" +
	"\x0eUpdateNameById\x12\".accounts.v1.UpdateNameByIdRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10v1/accounts/name\x12l\n" +
	"\x0fUpdateEmailById\x12#.accounts.v1.UpdateEmailByIdRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11v1/accounts/email\x12i\n" +
	"\x0eUpdateRoleById\x12\".accounts.v1.UpdateRoleByIdRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10v1/accounts/role\x12u\n" +
	"\x12UpdatePasswordById\x12&.accounts.v1.UpdatePasswordByIdRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14v1/accounts/password\x12Q\n" +
	"\x0eGetAccountById\x12\x0f.accounts.v1.Id\x1a\x14.accounts.v1.Account\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10v1/accounts/{id}\x12_\n" +
	"\x12GetAccountsByQuery\x12\x10.query.QueryData\x1a\".accounts.v1.QueryAccountsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\vv1/accountsB4Z2github.com/OddKuru/core-accounts/gogen/accounts/v1b\x06proto3"

var (
	file_accounts_v1_accounts_proto_rawDescOnce sync.Once
	file_accounts_v1_accounts_proto_rawDescData []byte
)

func file_accounts_v1_accounts_proto_rawDescGZIP() []byte {
	file_accounts_v1_accounts_proto_rawDescOnce.Do(func() {
		file_accounts_v1_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_v1_accounts_proto_rawDesc), len(file_accounts_v1_accounts_proto_rawDesc)))
	})
	return file_accounts_v1_accounts_proto_rawDescData
}

var file_accounts_v1_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_accounts_v1_accounts_proto_goTypes = []any{
	(*Id)(nil),                        // 0: accounts.v1.Id
	(*Account)(nil),                   // 1: accounts.v1.Account
	(*CreateAccountRequest)(nil),      // 2: accounts.v1.CreateAccountRequest
	(*UpdateNameByIdRequest)(nil),     // 3: accounts.v1.UpdateNameByIdRequest
	(*UpdateEmailByIdRequest)(nil),    // 4: accounts.v1.UpdateEmailByIdRequest
	(*UpdateRoleByIdRequest)(nil),     // 5: accounts.v1.UpdateRoleByIdRequest
	(*UpdatePasswordByIdRequest)(nil), // 6: accounts.v1.UpdatePasswordByIdRequest
	(*QueryAccountsResponse)(nil),     // 7: accounts.v1.QueryAccountsResponse
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
	(*v1.QueryData)(nil),              // 9: query.QueryData
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_accounts_v1_accounts_proto_depIdxs = []int32{
	8,  // 0: accounts.v1.Account.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 1: accounts.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: accounts.v1.QueryAccountsResponse.accounts:type_name -> accounts.v1.Account
	2,  // 3: accounts.v1.AccountsService.Create:input_type -> accounts.v1.CreateAccountRequest
	3,  // 4: accounts.v1.AccountsService.UpdateNameById:input_type -> accounts.v1.UpdateNameByIdRequest
	4,  // 5: accounts.v1.AccountsService.UpdateEmailById:input_type -> accounts.v1.UpdateEmailByIdRequest
	5,  // 6: accounts.v1.AccountsService.UpdateRoleById:input_type -> accounts.v1.UpdateRoleByIdRequest
	6,  // 7: accounts.v1.AccountsService.UpdatePasswordById:input_type -> accounts.v1.UpdatePasswordByIdRequest
	0,  // 8: accounts.v1.AccountsService.GetAccountById:input_type -> accounts.v1.Id
	9,  // 9: accounts.v1.AccountsService.GetAccountsByQuery:input_type -> query.QueryData
	1,  // 10: accounts.v1.AccountsService.Create:output_type -> accounts.v1.Account
	10, // 11: accounts.v1.AccountsService.UpdateNameById:output_type -> google.protobuf.Empty
	10, // 12: accounts.v1.AccountsService.UpdateEmailById:output_type -> google.protobuf.Empty
	10, // 13: accounts.v1.AccountsService.UpdateRoleById:output_type -> google.protobuf.Empty
	10, // 14: accounts.v1.AccountsService.UpdatePasswordById:output_type -> google.protobuf.Empty
	1,  // 15: accounts.v1.AccountsService.GetAccountById:output_type -> accounts.v1.Account
	7,  // 16: accounts.v1.AccountsService.GetAccountsByQuery:output_type -> accounts.v1.QueryAccountsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_accounts_v1_accounts_proto_init() }
func file_accounts_v1_accounts_proto_init() {
	if File_accounts_v1_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_v1_accounts_proto_rawDesc), len(file_accounts_v1_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_v1_accounts_proto_goTypes,
		DependencyIndexes: file_accounts_v1_accounts_proto_depIdxs,
		MessageInfos:      file_accounts_v1_accounts_proto_msgTypes,
	}.Build()
	File_accounts_v1_accounts_proto = out.File
	file_accounts_v1_accounts_proto_goTypes = nil
	file_accounts_v1_accounts_proto_depIdxs = nil
}
